### ISSUE TITLE
(Possible Enhancement) Touchscreen as DS4 touchpad, Motion controls available

### ISSUE THREAD

**Issue by dude98** [Eveldee/Eveldee.3DSCPlusViGEm#1]
I think it'd be pretty neat to be able to use the touchscreen as the DS4's touchpad, and be able to use the motion controls built into the 3ds with steam and programs that use cemuhook's motion control API (Dolphin emu, Citra, Cemu) it'd be awesome to have the ability to have the motion controls for slight camera adjustment (n3ds c stick ain't the best.) It'd be really nice to have the motion controls available, since i haven't really seen any homebrew for the 3ds make it usable yet.

**Comment by Eveldee** [comment]
This is sadly impossible to do with **ViGEm** at the moment, and I don't think it will be supported in a future update, so it's not possible using this library, I would have to use another one but it would make it harder to install/use/dev.
